          
version: '3'

services:
    tete_backend:
        build:
            context: ./backend/
            dockerfile: ./Dockerfile
        ports:
             - "8080:80"
    tete_frontend:
        build:
            context: ./frontend/
            dockerfile: ./Dockerfile
        depends_on:
             - tete_backend
        ports:
             - "80:1080"
