          
version: '3'

services:
    tecl_backend:
        build:
            context: ./backend/
            dockerfile: ./Dockerfile
        ports:
             - "8080:80"
    tecl_frontend:
        build:
            context: ./frontend/
            dockerfile: ./Dockerfile
        depends_on:
             - tecl_backend
        ports:
             - "80:1080"
